[Variables]

Default 	= SF UI Display Bold
DefaultBold 	= SF UI Display Heavy
IconFont0       = 
IconFont1       = Webdings
IconFont2       = Wingdings 2
IconFont3       = Wingdings
BarIcons        = Material Icons
CalendarMonth   = SF UI Regular
CalendarDay     = SF UI Regular
VolumePower     = SF UI Regular

ZeroSize        = 0
BarSize         = 10
SkinSize        = 10
BarTime         = 9
SysmonSize      = 12
SysmonInSize    = 12
SysmonTxtSize   = 9
SysmonDiskSize  = 10
SysmonMeterDisk = 14
SysmonBin       = 24
SysmonSetting   = 14
SysmonRainmeter = 10
CalendarMonthS  = 13
CalendarDayS    = 8
WeatherSize     = 16
WeatherCity     = 28
Icon_Font_Size  = 11

BarFontWeight   = 0